gen-go:
	protoc -I=/home/cuongtop/Desktop/Golang/src/github.com/cuongtop4598/chat_grpc_docker/proto \
		--go_out=/home/cuongtop/Desktop/Golang/src/github.com/cuongtop4598/chat_grpc_docker/proto \
		--go-grpc_out=/home/cuongtop/Desktop/Golang/src/github.com/cuongtop4598/chat_grpc_docker/proto \
		/home/cuongtop/Desktop/Golang/src/github.com/cuongtop4598/chat_grpc_docker/proto/chat.proto
